name: Release Pumpkin Build for Pi 5

on:
  schedule:
    - cron: '30 22 * * *'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-24.04-arm
    permissions:
      packages: write
      contents: read

    steps:
      - name: Get Latest Upstream Release Tag
        id: get_tag
        run: |
          RAW_TAG=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/Pumpkin-MC/Pumpkin/releases/latest | jq -r .tag_name)
          
          if [ -z "$RAW_TAG" ] || [ "$RAW_TAG" == "null" ]; then
            echo "Failed to fetch tag from GitHub. Exiting."
            exit 1
          fi

          SAFE_TAG=$(echo "$RAW_TAG" | sed 's/[^a-zA-Z0-9_.]/-/g')
          
          echo "git_tag=$RAW_TAG" >> $GITHUB_OUTPUT
          echo "docker_tag=$SAFE_TAG" >> $GITHUB_OUTPUT
          echo "Git Release: $RAW_TAG"
          echo "Docker Tag: $SAFE_TAG"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if this version is already built
        id: check_build
        run: |
          if docker manifest inspect ghcr.io/${{ github.repository_owner }}/pumpkin-mc:${{ steps.get_tag.outputs.docker_tag }} > /dev/null 2>&1; then
            echo "Version ${{ steps.get_tag.outputs.docker_tag }} already exists. Skipping the build."
            echo "build_needed=false" >> $GITHUB_OUTPUT
          else
            echo "Version ${{ steps.get_tag.outputs.docker_tag }} is new! Starting native compilation."
            echo "build_needed=true" >> $GITHUB_OUTPUT
          fi
    
      - name: Checkout your repository
        if: steps.check_build.outputs.build_needed == 'true'
        uses: actions/checkout@v4

      - name: Checkout upstream Pumpkin code
        if: steps.check_build.outputs.build_needed == 'true'
        run: |
          git clone --branch ${{ steps.get_tag.outputs.git_tag }} --depth 1 --recurse-submodules https://github.com/Pumpkin-MC/Pumpkin.git pumpkin-src
          cp Dockerfile.pi5 pumpkin-src/Dockerfile.pi5

      - name: Set up Docker Buildx
        if: steps.check_build.outputs.build_needed == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        if: steps.check_build.outputs.build_needed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./pumpkin-src
          file: ./pumpkin-src/Dockerfile.pi5
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/pumpkin-mc:latest
            ghcr.io/${{ github.repository_owner }}/pumpkin-mc:${{ steps.get_tag.outputs.docker_tag }}
